name: Auto-Clean

on:
  # Automatic cleaning: Every day at 7 AM
  schedule:
    - cron: 0 23 * * *
  # Manual cleaning
  workflow_dispatch:
    inputs:
      NUMBER:
        default: '4'
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: ${{inputs.NUMBER || '4'}}
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
