#CI Project
name: QCA-ALL

#CI Plan
on:
  # Automatic cleaning: Every day at 5 AM
  schedule:
   - cron: 0 21 * * *
  # Automatic compilation: After Auto-Clean is completed
  #workflow_run:
  #  workflows: ["Auto-Clean"]
  #  types:
  #   - completed
  # Manual compilation
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: 'Manually adjust the plugin package, limited to one.'
        required: false
        type: string
      TEST:
        description: 'Only output the configuration file, do not compile the firmware'
        default: false
        required: false
        type: boolean
      COMMIT:
        description: 'Specify Commit.'
        required: false
        type: string


#CI Permissions
permissions: write-all

#CI Jobs
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 2
      matrix:
        TARGET: [IPQ60XX-WIFI]
        REPO_INFO:
          - {SOURCE: coolsnowwolf/lede, BRANCH: master, NAME: LEDE, SUFFIX: LEDE}
          #- {SOURCE: coolsnowwolf/lede, BRANCH: master, NAME: LEDE-FW4, SUFFIX: LEDE-FW4}
          #- {SOURCE: VIKINGYFY/immortalwrt, BRANCH: main, NAME: OWRT, SUFFIX: IMM}
          #- {SOURCE: LiBwrt-op/openwrt-6.x, BRANCH: openwrt-24.10, NAME: LibWRT, SUFFIX: IMM}
          #- {SOURCE: immortalwrt/immortalwrt, BRANCH: openwrt-24.10, NAME: ImmortalWRT, SUFFIX: IMM}

    # Call the public compilation core WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      # Compilation platform
      WRT_TARGET: ${{matrix.TARGET}}
      # Default theme
      WRT_THEME: argon
      # Default hostname
      WRT_NAME: ${{matrix.REPO_INFO.NAME}}
      # Default address
      WRT_IP: 192.168.1.1
      # Default password, just for reference, modification is useless
      WRT_PW: password
      # Source link
      WRT_REPO: https://github.com/${{matrix.REPO_INFO.SOURCE}}.git
      # Source branch
      WRT_BRANCH: ${{matrix.REPO_INFO.BRANCH || 'main'}}
      # Source name
      WRT_SOURCE: ${{matrix.REPO_INFO.SOURCE}}
      # Source COMMIT
      WRT_COMMIT: ${{inputs.COMMIT}}
      # Suffix name
      WRT_SUFFIX: ${{matrix.REPO_INFO.SUFFIX}}
      # Plugin adjustment
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      # Only output the configuration file
      WRT_TEST: ${{inputs.TEST}}
